### ISSUE TITLE
Can't compile in  VS  2019:  missing MFC libraries

### ISSUE THREAD

**Issue by billwoo** [baradzenka/TabCtrl#1]
Opened latest version here.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8041	MFC libraries are required for this project. Install them from the Visual Studio installer (Individual Components tab) for any toolsets and architectures being used.	TabCtrl	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	479

**Comment by baradzenka** [comment]
**My VS version and installed components::**
Microsoft Visual Studio Community 2019
Version 16.9.2
![pic](https://user-images.githubusercontent.com/78237661/111544695-9d897a00-8753-11eb-803b-846996c5f095.png)

**Comment by billwoo** [comment]
thanks !
